---
title: "PCA_plots"
output: html_document
---
## load dependencies
```{r setup}
library(crayon)
library(tidyverse)
library(pcaMethods)
library(gridExtra)

get_legend <- function(myggplot) {
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
```

## import data
```{r import data}
gxData <- read.delim("./Data/MAGNET_GeneExpressionData_CPM_19112020.txt", as.is = T, row.names = 1)

sampleInfo <- read.delim("./Data/MAGNET_SampleData_19112020.txt", as.is = T, row.names = 1)
sampleInfo <- sampleInfo %>% mutate(
  Disease = factor(Disease, levels = unique(Disease)),
  Sex = factor(Sex, levels = unique(Sex)),
  Ethnicity = factor(Ethnicity, levels = unique(Ethnicity))
)

sampleInfoExtended <- read.delim("https://raw.githubusercontent.com/mpmorley/MAGNet/master/phenoData.csv", sep = ",", as.is = T)
sampleInfoExtendedClean <- sampleInfoExtended %>% 
  mutate(
    Disease = factor(etiology, levels = unique(etiology), labels = levels(sampleInfo$Disease)),
    Ethnicity = factor(race, levels = unique(race), labels = levels(sampleInfo$Ethnicity)),
    BMI = round(weight / (height/100)^2, digits = 1),
    Sex = factor(gender),
    Diabetes = as.logical(factor(Diabetes, levels = c("Yes", "No"), labels = c("TRUE", "FALSE"))),
    Hypertension = as.logical(factor(Hypertension, levels = c("Yes", "No"), labels = c("TRUE", "FALSE"))),
    Atrial.Fibrillation = as.logical(factor(afib, levels = c("Yes", "No"), labels = c("TRUE", "FALSE"))),
    VTVF = as.logical(factor(VTVF, levels = c("Yes", "No"), labels = c("TRUE", "FALSE")))
  ) %>% 
  relocate(c("Disease", "Ethnicity", "Sex", "Diabetes", "Hypertension", "Atrial.Fibrillation", "VTVF", "BMI", "age", "LVEF"), .after = "sample_name") %>% 
  dplyr::select(-c("etiology", "race", "gender", "afib", "disease_race")) %>%
  dplyr::rename("Age" = "age", "LV.EjectionFraction" = "LVEF")
```

#### PCA
```{r calculate PCA}
cat("\nCalculating PCAs...\n")

pcaRes <- pcaMethods::pca(t(gxData), nPcs = 10)
pcaResScores <- pcaRes@scores %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample_name")
PCAplotData <- sampleInfoExtendedClean %>%
  select(c(1:11)) %>%
  right_join(pcaResScores, by = "sample_name") %>%
  column_to_rownames(var = "sample_name")
rm("pcaRes", "pcaResScores")
```

## PCA plots loop (experimental), creates 45 .tiff files requiring ~1.7GB
```{r visualize PCA scores}
# I would like to put this in a loop, but creating all possible combinations without duplication or combining a PC with itself seems difficult
# and renaming objects during a loop according to its content appears impossible

if(fs::dir_exists("output/PCA")) {
    cat(cyan("'output/PCA' already exists in: "), getwd(), sep = "")
  } else {
    cat(cyan("'output/PCA' created in: "), getwd(), sep = "")
    fs::dir_create("output/PCA")
  }

PC_comb <- t(combn(x = (1:10), 2)) %>%
  data.frame() %>%
  rename("Component_1" = "X1", "Component_2" = "X2") %>%
  mutate(
    Component_1 = paste("PC", Component_1, sep = ""),
    Component_2 = paste("PC", Component_2, sep = ""),
    Name = paste(Component_1, "_", Component_2, sep = "")
  )
coVariates <- colnames(PCAplotData)[1:10]

for (comb in 1:nrow(PC_comb)) {
  
  cat(yellow$underline("\n<<<<< creating plots for", PC_comb[comb, "Name"], ">>>>>\n"), sep = " ")
  
  # add colours by variables
  for (coVariate in coVariates) {
    cat(green("\ncoloring plot by", italic(coVariate), "\n"), sep = " ")
    
    c1 <- PC_comb[comb, 1]; c2 <- PC_comb[comb, 2]
    
    PCAplotTemp <- PCAplotData %>% ggplot() +
      theme(
        panel.background = element_blank(),
        plot.background = element_blank(),
        title = element_text(size = 10),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.direction = "horizontal"
        #legend.position = "none"
      )  + 
      geom_point(
        aes(x = .data[[c1]], y = .data[[c2]], color = .data[[coVariate]], size = 3, alpha = 0.5, stroke = 1.1)
      ) +
      xlab(c1) +
      ylab(c2) + 
      ggtitle(coVariate)
    
    if (coVariate %in% coVariates[8:10]) {
      # color by continuous variables and assign to object
      cat("continuous\nmax = ", max(PCAplotData[, coVariate], na.rm = T), "\nmin = ", min(PCAplotData[, coVariate], na.rm = T), "\ncolors:", round(max(PCAplotData[, coVariate], na.rm = T) + 0.5, digits = 0) - round(min(PCAplotData[, coVariate], na.rm = T) - 0.5, digits = 0), "\n")
      
      #continuous_scale() +
      PCAplotTemp <- PCAplotTemp + scale_color_gradientn(colors = viridisLite::viridis(
        n = 256, option = "D", begin = 0.1, end = 0.9)
      )
      
    } else if (coVariate %in% coVariates[1:7]) {
      # color by discrete variables and assign to object
      cat("discrete, colors:", length(unique(na.omit(PCAplotData[, coVariate]))), "\n")
      
      #discrete_scale() +
      PCAplotTemp <- PCAplotTemp + scale_color_manual(values = viridisLite::viridis(
        n = length(unique(na.omit(PCAplotData[, coVariate]))), option = "D", begin = 0.1, end = 0.9)
      )
      
    }
    
    PCAplotTemp <- PCAplotTemp + guides(size = "none", alpha = "none")
    leg <- get_legend(PCAplotTemp)
    PCAplotTemp <- PCAplotTemp + theme(legend.position = "none")
    
    assign(paste(coVariate, sep = ""), PCAplotTemp)
    assign(paste("leg_", coVariate, sep = ""), leg)
    rm(PCAplotTemp, leg)
    
  }
  
  cat("combine plots and save file ", yellow(paste("plot_", PC_comb[comb, "Name"], ".png", sep = "")), "\nfile path: ", getwd(), "\n\n", sep = "")
  
  p <- gridExtra::arrangeGrob(get(coVariates[1]), get(coVariates[2]), get(coVariates[3]), get(coVariates[4]), get(coVariates[5]),
                              get(paste("leg_", coVariates[1], sep = "")), get(paste("leg_", coVariates[2], sep = "")), get(paste("leg_", coVariates[3], sep = "")), get(paste("leg_", coVariates[4], sep = "")), get(paste("leg_", coVariates[5], sep = "")), 
                              get(coVariates[6]), get(coVariates[7]), get(coVariates[8]), get(coVariates[9]), get(coVariates[10]),
                              get(paste("leg_", coVariates[6], sep = "")), get(paste("leg_", coVariates[7], sep = "")), get(paste("leg_", coVariates[8], sep = "")), get(paste("leg_", coVariates[9], sep = "")), get(paste("leg_", coVariates[10], sep = "")),
                              ncol = 5, nrow = 4,
                              widths = c(1,1,1,1,1), heights = c(4,1,4,1)
  )
  ggsave(filename = paste("plot_", PC_comb[comb, "Name"], ".tiff", sep = ""),
         plot = p,
         device = "tiff",
         path = "output/PCA",
         width = 15,
         height = 10
  )
  
  dev.off() # necessary for png()
  rm(list = c(coVariates, ls()[grep("leg_", ls())]))
  rm(p)
}
rm("coVariates", "PC_comb", "PCAplotTemp", "comb", "coVariate", "c1", "c2")
```